<?php
defined("ABSPATH") or die("");
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit147d975ecce5503891fdee3de27a500f::getLoader();
