<?php
defined("ABSPATH") or die("");
// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Sami' => array($vendorDir . '/sami/sami'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'PHPParser' => array($vendorDir . '/nikic/php-parser/lib'),
    'Michelf' => array($vendorDir . '/michelf/php-markdown'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src'),
);
