<?php
defined("ABSPATH") or die("");
// include_paths.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $baseDir . '/phpseclib',
    $vendorDir . '/phing/phing/classes',
    $vendorDir . '/phpunit/php-text-template',
    $vendorDir . '/phpunit/php-timer',
    $vendorDir . '/phpunit/php-file-iterator',
);
